# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
